swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /knowledgeSim:
    post:
      operationId: controller.POST_synonyms_similarity
      tags:
        - Model based on knowledge
      summary: Compute similarity between two sentences.
      description: Compute similarity between two sentences.
      parameters:
        - name: params
          in: body
          description: Parameters
          required: True
          schema:
            type: object
            properties:
              sent1:
                type: string
                description: First sentence
              sent2:
                type: string
                description: Second sentence
      responses:
        201:
          description: Successfully
  /corpusSim:
    post:
      operationId: controller.POST_w2v_similarity
      tags:
        - Model based on corpus
      summary: Compute similarity between two sentences.
      description: Compute similarity between two sentences.
      parameters:
        - name: params
          in: body
          description: Parameters
          required: True
          schema:
            type: object
            properties:
              sent1:
                type: string
                description: First sentence
              sent2:
                type: string
                description: Second sentence
      responses:
        201:
          description: Successfully